version: "3.6"
services:
  web:
    build: .
    image: registry.dis.cwi.nl/traction-encoding-api
    restart: always
    volumes:
      - ./aws.json:/code/aws.json
      - ./.env:/code/.env
      - ./bin:/code/bin
      - ./db:/code/db
    ports:
      - "3001:3000"
    command: yarn start
    environment:
      - NODE_ENV=development
    logging:
      options:
        max-size: "200k"
        max-file: "3"
