services:
  web:
    build: .
    image: traction-encoding-api-production
    volumes:
      - ./aws.json:/code/aws.json
      - ./.env:/code/.env
      - ./db:/code/db
    ports:
      - "3001:3000"
    command: yarn start
    environment:
      - NODE_ENV=production
    logging:
      options:
        max-size: "200k"
        max-file: "3"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
